name: "<div dir="rtl">‏🐞 تَقريرُ خَطَأ‏</div>"
description: "<div dir="rtl">‏الإبلاغُ عَن خَطَإٍ في لَوحةِ المَفاتيحِ العَرَبِيّةِ‏</div>"
title: "<div dir="rtl">‏خَطَأ:‏ </div>"
labels: ["bug"]
assignees: []
body:
  - type: textarea
    id: problem-description
    attributes:
      label: "<div dir="rtl">‏ما هِيَ المُشكِلة؟</div>"
      description: "<div dir="rtl">‏صِف المُشكِلةَ الَّتي تواجِهُها بِوُضوحٍ وَإيجاز.</div>"
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "<div dir="rtl">‏كَيفَ يُمكِنُنا إعادةُ إنتاجِ المُشكِلة؟</div>"
      description: "<div dir="rtl">‏أُذكُرِ الخُطواتِ التَّفصيلِيّةَ لِإعادةِ إنتاجِ الخَطَأ.</div>"
      placeholder: |
        <div dir="rtl">‏1. ‏إفتَح ‏'...'</div>
        <div dir="rtl">‏2. ‏أُكتُب ‏'...'</div>
        <div dir="rtl">‏3. ‏لاَحِظِ المُشكِلة</div>
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: "<div dir="rtl">‏ما الَّذي تَوَقَّعتَ حُدوثَه؟</div>"
      description: "<div dir="rtl">‏صِف ما تَوَقَّعتَ رُؤيَتَهُ بَدَلاً مِنَ الخَطَأ.</div>"
    validations:
      required: false
  - type: checkboxes
    id: context-product
    attributes:
      label: "<div dir="rtl">‏مِنَصّةُ Keyman</div>"
      description: "<div dir="rtl">‏أَيُّ تَطبيقِ Keyman تَستَخدِم؟</div>"
      options:
        - label: "<div dir="rtl">‏Keyman ‏لِنِظامِ ‏Android</div>"
        - label: "<div dir="rtl">‏Keyman ‏لِنِظامِ ‏iPhone وَ ‏iPad</div>"
        - label: "<div dir="rtl">‏Keyman ‏لِنِظامِ ‏Linux</div>"
        - label: "<div dir="rtl">‏Keyman ‏لِنِظامِ ‏macOS</div>"
        - label: "<div dir="rtl">‏Keyman ‏لِنِظامِ ‏Windows</div>"
        - label: "<div dir="rtl">‏Keyman Developer</div>"
        - label: "<div dir="rtl">‏KeymanWeb</div>"
  - type: input
    id: keyman-version
    attributes:
      label: "<div dir="rtl">‏إصدارُ تَطبيقِ Keyman</div>"
      placeholder: "<div dir="rtl">‏مِثال: 16.0.140</div>"
  - type: checkboxes
    id: arabiyy-keyboard
    attributes:
      label: "<div dir="rtl">‏نَوعُ لَوحةِ المَفاتيحِ العَرَبِيّة</div>"
      description: "<div dir="rtl">‏أَيُّ إصدارٍ مِن لَوحةِ المَفاتيحِ العَرَبِيّةِ تَستَخدِم؟</div>"
      options:
        - label: Arabiyy
        - label: ArabiyyNumOnShift
        - label: ArabiyyMobile
  - type: textarea
    id: additional-info
    attributes:
      label: "<div dir="rtl">‏أَيُّ مَعلوماتٍ إضافِيّة؟</div>"
      description: "<div dir="rtl">‏أَضِف سِجِلاَّت، لَقَطاتِ شاشة، مَشاكِلَ ذاتَ صِلة، أَو مَعلوماتٍ مُفيدةً أُخرى.</div>"